# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mohae' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mohae
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod "GSKStretchyHeaderView"
  pod 'SnapKit', '~> 5.0'
  target 'MohaeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MohaeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
