# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mohae' do

  # Pods for Mohae
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SnapKit', '~> 5.0'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth' 
  target 'MohaeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MohaeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
